### ISSUE TITLE
How do I install this version of nest?

### ISSUE THREAD

**Issue by Tss20** [gmtiddia/nest-simulator-3.1#3]
I want to install this version of NEST with conda but since it's not 3.1, I'm not actually sure which version this is. I cannot find any information regarding this on the website.

**Comment by gmtiddia** [comment]
Indeed, this version is derived from the NEST 3.1 release and edited to add a new synapse model. Such a modification currently prevents this version of NEST from being installed using conda or PPA, since such approaches would install version 3.1 without the modifications performed in this repository. I installed this version on Ubuntu 21.10 and 22.04 following the installation instructions on the NEST Documentation for the advanced Ubuntu/Debian installation. 

To clarify this, I updated the README of this repository to provide more instructions for the installation and more details on the new synapse model implemented.

**Comment by gmtiddia** [comment]
Hi!
This version of NEST is no longer needed to run the model. If you have NEST (any 3.x version would work) and NESTML (both can be installed using conda) with the network model of  [this repository](https://github.com/gmtiddia/working_memory_spiking_network) you have the same results!
